version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=online2
    
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:        
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

  app:
    image: ghcr.io/mostafatahboub/online-examination-system-1:$GIT_VERSION
    restart: always
    environment:
      - PORT=80
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=online2
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: