version: '3'

services:
  mysql:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    

  app:
    profiles:
      - in_docker
    container_name: OnlineExaminationSystem
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - "3000:80"
    depends_on:      
      mysql:
        condition: service_healthy

volumes:
  db-data: