name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      ec2_ips: ${{ steps.get_instance_ips.outputs.ips }}
      image_version: ${{ steps.image_version.outputs.gitsha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image version (tag)
        id: image_version
        run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mostafatahboub
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/mostafatahboub/online-examination-system-1:${{ steps.image_version.outputs.gitsha }}

      - name: Publish Docker image
        run: docker push ghcr.io/mostafatahboub/online-examination-system-1:${{ steps.image_version.outputs.gitsha }}

      - name: Get EC2 instance IPs
        id: get_instance_ips
        run: |
          instances=$(aws ec2 describe-instances --filters 'Name=tag:aws:autoscaling:groupName,Values=online-exam-asg'
               --query 'Reservations[*].Instances[*].PublicIpAddress' --output json | jq -c 'flatten')
          echo "ips=$instances" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    needs: ['build']
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ip: ${{fromJson(needs.build.outputs.ec2_ips)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker host
        uses: khaledez/configure-docker-host@v1
        with:
          host: ${{ matrix.ip }}
          user: github
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mostafatahboub
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: docker compose -f docker-compose-prod.yml up -d
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GIT_VERSION: ${{ needs.build.outputs.image_version }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
